# Generated by Django 5.2.4 on 2025-07-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Failed', 'Failed')], default='Sent', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(default='WhatsApp', max_length=50)),
            ],
        ),
    ]
