# Generated by Django 5.2.4 on 2025-08-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('Regular', 'Regular'), ('Student', 'Student')], default='Regular', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('renewal_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
