# Generated by Django 5.2.4 on 2025-07-31 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0002_initial'),
        ('reservation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlocation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_locations', to='users.user'),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_locations', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.location'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.user'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.location'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_slots',
            field=models.ManyToManyField(to='reservation.timeslot'),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.timeslot'),
        ),
    ]
