# Generated by Django 5.2.4 on 2025-08-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='subscription_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Student', 'Student')], default='Regular', max_length=20),
        ),
    ]
