# Generated by Django 5.2.4 on 2025-07-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='client',
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
