# Generated by Django 5.2.4 on 2025-08-08 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_meetingpoint_location_meeting_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
    ]
