# Generated by Django 5.2.4 on 2025-07-31 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        ('reservation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_missions', to='users.user'),
        ),
        migrations.AddField(
            model_name='mission',
            name='reservations',
            field=models.ManyToManyField(related_name='missions', to='reservation.reservation'),
        ),
    ]
