# Generated by Django 5.2.4 on 2025-08-05 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_alter_mission_agent'),
        ('reservation', '0004_remove_reservation_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='reservation.location'),
        ),
    ]
